### PR TITLE
Write Quiver logs from docker container to syslogs

### PR DESCRIPTION
**Pull request by dborkan**
Write Quiver logs from docker container to syslogs, so that we can easily grep through them as before, and they will rotate/zip as they grow too long

### CODE REVIEW

**Comment by bemasc** [comment]
:+1:

**Comment by trevj** [comment]
FYI, this fails on both my Linux box (1.9.1) and my OSX laptop (1.12.0 RC3). What version of Docker are you running?:
```
trevj@trevj02:~/src/uproxy-docker$ ./install-quiver.sh 
flag provided but not defined: --log-tag
See 'docker run --help'.
```

I had to change the command to read:
```bash
docker run --restart=always --name uproxy-quiver --log-driver=syslog --log-opt tag=quiver -d -p 80:3000 uproxy/quiver
```

BTW, do you know how to read the logs syslog on OSX? It runs although I don't see any quiver messages in `/var/log/system.log`.

**Comment by dborkan** [comment]
Good catch, I actually ran ```docker run --restart=always --log-driver=syslog --log-opt tag=quiver --name uproxy-quiver -d -p 80:3000 uproxy/quiver``` on my machine as well and think I must have made some dumb error when copying+pasting that command to install-quiver.sh.  Just updated the pull request with that

**Comment by trevj** [comment]
Cool. I think we may need to revisit this at some stage - specifying syslog is a little too platform-specific than I'd like - but it seems fine for now as it's mostly just us running these things.

:+1:

**Comment by jab** [comment]
@trevj wrote:
> BTW, do you know how to read the logs syslog on OSX? It runs although I don't see any quiver messages in /var/log/system.log.

@trevj this works for me, does it work for you?
```
$ syslog -s -l notice "testing testing 1 2 3" && tail -1 /var/log/system.log
Jul 28 15:28:50 qux.local syslog[46201]: testing testing 1 2 3
```

(((
I had to set level to `notice` for it to show up. Looks like my (stock) `/etc/asl.conf` configures that as the loglevel that's in effect:
```
...
# Rules for /var/log/system.log
> system.log mode=0640 format=bsd rotate=seq compress file_max=5M all_max=50M
...
? [<= Level notice] file system.log
...
```
)))

(Also the /Applications/Utilities/Console.app GUI can be handy sometimes fwiw)

**Pull request merged**
