### PR TITLE
release helper for uproxy-lib

### PR DESCRIPTION
**Pull request by trevj**
As part of:
https://github.com/uProxy/uproxy/issues/1745

I'm hoping this script can become the automated part of the release process for uproxy-lib. It starts by fetching a simple web page and computing its md5sum. Then, for all possible getter/giver configurations it tries to fetch the same page via the proxy, comparing each time the md5sum of the received page with the known-good md5sum. If the sum matches, that getter/giver configuration is marked as good.

In the end, outputs some markdown which we can include in release notes, e.g.:

| * | chrome-stable | chrome-beta | chrome-canary | firefox-stable | firefox-beta | firefox-canary |
| --: | :-: | :-: | :-: | :-: | :-: | :-: |
| chrome-stable | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: | :x: | :x: |
| chrome-beta | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: | :x: | :x: |
| chrome-canary | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: | :x: | :x: |
| firefox-stable | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: | :x: | :x: |
| firefox-beta | :x: | :x: | :x: | :x: | :x: | :x: |
| firefox-canary | :x: | :x: | :x: | :x: | :x: | :x: |

Takes about 8 minutes to run on my 3.5GHz Xeon.

### CODE REVIEW

**Comment by trevj** [comment]
Update: in addition to the small curl, I added a larger (16MB) transfer test.

**Comment by trevj** [comment]
Update: actually check the hash of the large file download test.

**Comment by trevj** [comment]
Update: I am seeing random failures with 16MB downloads. I've made it 1MB - which seems to be fine on all platforms - and filed an issue to investigate:
https://github.com/uProxy/uproxy/issues/1835

**Comment by mollyling** [comment]
This is really awesome :+1:

**Pull request merged**
