### PR TITLE
reduce key length to get invite URLs below 2000 characters

### PR DESCRIPTION
**Pull request by trevj**
1500 bits makes for URLs of ~1800 characters. Seems like a decent trade-off between security and convenience.

### CODE REVIEW

**Comment by trevj** [comment]
@dborkan You reckon ~1800 characters is good? Seems to work fine now with IM and the URL handler on the website.

**Comment by dborkan** [comment]
Yeah that sounds good - AFAIK 2000 characters is a common limit (e.g. in
Google Hangouts)

**Comment by soycode** [comment]
I'd say switch to 1536 (1024+512) just to be a little multiple-of-2 closer, which also makes it a little bit less non-standard (https://en.wikipedia.org/wiki/RSA_numbers#RSA-1536).

The other concern is whether 1536 bit keys are "good enough" - most security recommendations (https://www.keylength.com/en/4/) list 1024 as legacy and 2048 as recommended. Of course, the particularly security-conscious are saying to get away from RSA completely (https://gist.github.com/tqbf/be58d2d39690c3b366ad), which is ultimately our goal but we can't switch quite yet.

My opinion is that yes, this is probably good enough for us for now (as we intend to switch well before 2030, the recommended "good until" year for 2048), but if there is anybody else who should be flagged for security-sensitive changes then it'd be good to involve them.

**Comment by trevj** [comment]
Excellent point. Changed to 1536. Thanks!

**Comment by trevj** [comment]
PTAL!

**Comment by soycode** [comment]
Then a I'm-not-actually-a-crypto-guy-caveated :+1: from me. 1536 bit is a bit of a "boutique" key size, but with how exponential growth works it seems like a defensible choice. If we want to try to rationalize/measure the tradeoff here, it'd be good to at least estimate the % of users likely deterred by >2000 character invitations. If it's fairly substantial then I'd say this is worth it.

**Comment by trevj** [comment]
Thanks :-)

Yes, understood, I'd be very surprised if someone thinks it's worth breaking 1536 keys just for signalling messages - OTOH, I know being unpasteable is a pretty big hindrance for most users.

**Pull request merged**
