### PR TITLE
some fixes for mac users

### PR DESCRIPTION
**Pull request by trevj**
OK, been travelling and here's a bunch of fixes to make `run_pair.sh` work on Mac.

### CODE REVIEW

**Comment by mollyling** [comment]
:+1:

**Comment by trevj** [comment]
Looks like a bunch of things were introduced that break on Mac; I'll have to revisit this when I'm back after holidays.

**Comment by mollyling** [comment]
Ugh, sorry.


Cheers,
$ ls

Lally Singh | Google Ideas <http://www.google.com/ideas/> | Engineering |
lally@google.com

**Comment by trevj** [comment]
Sorry, looks like the fixes required are pretty minor -- worse is that Docker seems to be down right now, I can't pull any new images :-)

**Comment by trevj** [comment]
Mystery solved: there's something about operator precedence that bash on Mac doesn't like. I just had to change these lines from:
```bash
source "${BASH_SOURCE%/*}/utils.sh" || echo "cannot find utils.sh" && exit 1
```
to
```bash
source "${BASH_SOURCE%/*}/utils.sh" || (echo "cannot find utils.sh" && exit 1)
```
Since that line was my suggestion, seems only fair I should fix it :-)

**Pull request merged**
